largura=float(input('Largura da parede:'))
altura=float(input('Altura da parede:'))
area=float(largura*altura)
print('Sua parede tem a dimensão de {} x {} e sua área é de {}m2'.format(largura, altura, area))
print('Para pintar sua parede é necessario {}l de tinta'.format(area/2))